services:
  booking:
    build: ./booking
    ports:
      - "3001" 
    networks:
      - mern_network
    environment:
      MONGO_URL: mongodb+srv://Sujal:Admin123@cluster0.ig5deah.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 
      PORT: 3001 
      
  payment:
    build: ./payment
    ports:
      - "5070" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb+srv://Bhavesh:Admin123@cluster0.ig5deah.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 
      PORT: 5070
      
  login:
    build: ./login
    ports:
      - "5050" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb+srv://Kavya:Admin123@cluster0.ig5deah.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0  
      PORT: 5050
      JWT_SECRET: y2cjouqyr
      
  nginx-proxy:
    build: ./nginx-proxy
    ports:
      - "80:80" 
    networks:
      - mern_network
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      args:
        VITE_LOGIN_API_URL: /api/login
        VITE_PAYMENT_API_URL: /api/payment
        VITE_BOOKING_API_URL: /api/booking
    ports:
      - "80"  
    networks:
      - mern_network
    environment:
      VITE_LOGIN_API_URL: /api/login
      VITE_PAYMENT_API_URL: /api/payment
      VITE_BOOKING_API_URL: /api/booking
    depends_on:
      - booking
      - payment
      - login

networks:
  mern_network:
    driver: bridge 

