name: nginx-proxy-microservice
on:
  pull_request:
    branches:
      - nginx-proxy

permissions:
  contents: read
  id-token: write
  
jobs:


  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        env:
          ECR_IMAGE_URI: 831926586767.dkr.ecr.us-east-1.amazonaws.com/travelease/nginx-proxy
          IMAGE_TAG: ${{ github.run_id }}
        run: |
          docker build -t $ECR_IMAGE_URI:$IMAGE_TAG .

  updatek8s:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone external repo to get token
        run: |
          curl -L "https://drive.google.com/uc?export=download&id=1sJWDNbhHEpt8BYtBbW3MI65clSsktwAu" -o token.txt
          token=$(cat token.txt | tr -d '\n')
          echo "TOKEN=$token" >> $GITHUB_ENV

      - name: Checkout again with dynamic token
        uses: actions/checkout@v4
        with:
          token: ${{ env.TOKEN }}

      - name: Update tag in kubernetes deployment manifest
        run: |
          sed -i "s|image: .*|image: 831926586767.dkr.ecr.us-east-1.amazonaws.com/travelease/nginx-proxy:${{ github.run_id }}|" kubernetes/deploy.yml
          sed -i "s|IMAGE_TAG = .*|IMAGE_TAG = ${{ github.run_id }}|" Jenkinsfile

      - name: Commit and push changes
        run: |
          git config --global user.email "madhujeet111@gmail.com"
          git config --global user.name "kavya-singh101"
          git add .
          git commit -m "[CI]: Update nginx-proxy image tag"
          git push origin HEAD:nginx-proxy -f
